/**
 * Generates src/data/verses.ts with authentic World English Bible (public
 * domain) text for a curated ~360-day reference list.
 *
 * Source: local WEB JSON (TehShrike/world-english-bible), cloned into
 * scratchpad. Set WEB_JSON_DIR to the json/ folder. No network, no rate limits.
 *   WEB_JSON_DIR=/path/to/web-bible/json node scripts/fetch-verses.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const JSON_DIR =
  process.env.WEB_JSON_DIR ??
  '/tmp/claude-0/-home-user-Dailyprayer/f91ded5e-aea9-5d96-8382-fec692f22844/scratchpad/web-bible/json';

import { CURATED } from './curated-refs.mjs';

// Map spoken book names -> WEB json filenames.
const FILE = (book) => book.toLowerCase().replace(/\s+/g, '') + '.json';
const NAME_FIX = { 'psalm': 'psalms', 'song of solomon': 'songofsolomon', 'songofsolomon': 'songofsolomon' };

const cache = new Map();
function loadBook(book) {
  const key = NAME_FIX[book.toLowerCase()] ?? book.toLowerCase().replace(/\s+/g, '');
  if (cache.has(key)) return cache.get(key);
  const path = join(JSON_DIR, `${key}.json`);
  if (!existsSync(path)) throw new Error(`no file ${key}.json`);
  const data = JSON.parse(readFileSync(path, 'utf8'));
  cache.set(key, data);
  return data;
}

function parseRef(ref) {
  // "1 Corinthians 13:4-5" -> { book, chapter, v1, v2 }
  const m = ref.match(/^(\d?\s?[A-Za-z ]+?)\s+(\d+):(\d+)(?:-(\d+))?$/);
  if (!m) throw new Error(`bad ref ${ref}`);
  const [, book, ch, a, b] = m;
  return { book: book.trim(), chapter: +ch, v1: +a, v2: b ? +b : +a };
}

function verseText(ref) {
  const { book, chapter, v1, v2 } = parseRef(ref);
  const data = loadBook(book);
  const parts = [];
  for (const node of data) {
    if (
      (node.type === 'line text' || node.type === 'paragraph text') &&
      node.chapterNumber === chapter &&
      node.verseNumber >= v1 &&
      node.verseNumber <= v2 &&
      typeof node.value === 'string'
    ) {
      parts.push(node.value);
    }
  }
  const text = parts.join(' ').replace(/\s+/g, ' ').replace(/\s+([,.;:!?])/g, '$1').trim();
  if (!text) throw new Error(`empty ${ref}`);
  return text;
}

const entries = [];
const failed = [];
const seen = new Set();
for (const [group, refs] of Object.entries(CURATED)) {
  // Expansion groups are suffixed (peace2, strength2…); map back to the real
  // theme so every verse still keys a valid A5 art series.
  const theme = group.replace(/\d+$/, '');
  for (const ref of refs) {
    if (seen.has(ref)) continue; // a verse belongs to its first theme only
    seen.add(ref);
    try {
      entries.push({ text: verseText(ref), reference: ref, theme });
    } catch (e) {
      failed.push(`${ref}: ${e.message}`);
    }
  }
}

// Interleave themes so consecutive days vary.
const byTheme = {};
for (const e of entries) (byTheme[e.theme] ??= []).push(e);
const pools = Object.values(byTheme);
const interleaved = [];
let added = true;
while (added) {
  added = false;
  for (const pool of pools) {
    const item = pool.shift();
    if (item) { interleaved.push(item); added = true; }
  }
}

const themeUnion = [...new Set(Object.keys(CURATED).map((g) => g.replace(/\d+$/, '')))]
  .map((t) => `'${t}'`)
  .join(' | ');
const body = interleaved
  .map((e) => `  { text: ${JSON.stringify(e.text)}, reference: ${JSON.stringify(e.reference)}, theme: '${e.theme}' },`)
  .join('\n');

const OUT = new URL('../src/data/verses.ts', import.meta.url).pathname;
writeFileSync(
  OUT,
  `/**
 * Daily verses — World English Bible (public domain).
 * GENERATED by scripts/fetch-verses.mjs from the WEB JSON source — edit the
 * curated reference list in that script, not this file. ${interleaved.length} entries,
 * theme-interleaved for day-of-year rotation.
 */
export interface DailyVerse {
  text: string;
  reference: string;
  theme: ${themeUnion};
}

export const verses: DailyVerse[] = [
${body}
];
`,
);

console.log(`Wrote ${interleaved.length} verses to src/data/verses.ts`);
if (failed.length) {
  console.log(`Failed (${failed.length}):`);
  failed.forEach((f) => console.log(' -', f));
}
